# =================================================================
# INFRASTRUCTURE MANIFEST
# Contains only the database for the auth-service.
# =================================================================
apiVersion: v1
kind: Service
metadata:
  name: auth-db-svc
  namespace: lirmm-services
spec:
  selector:
    app: auth-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db-deployment
  namespace: lirmm-services
  labels:
    app: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
      annotations:
        sidecar.istio.io/inject: "false" # Exclude infra from mesh
    spec:
      containers:
      - name: auth-db
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "auth_db"
        volumeMounts:
        - name: auth-db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: auth-db-data
        emptyDir: {}