# In kind-cluster-config.yaml

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # Istio Ingress Gateway
  - containerPort: 30000
    hostPort: 13000
    protocol: TCP
  # Kafka
  # --- FIX: Change the containerPort to avoid collision ---
  - containerPort: 30992
    hostPort: 29092
    protocol: TCP
  # --- END FIX ---
  # Elasticsearch
  - containerPort: 32200
    hostPort: 9200
    protocol: TCP
  # Redis
  - containerPort: 32379
    hostPort: 6379
    protocol: TCP