kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # This maps the Istio Ingress Gateway's HTTP NodePort to your host machine.
  - containerPort: 30000
    hostPort: 13000
    protocol: TCP
  # This maps the Consul UI port to your host machine.
  - containerPort: 32500
    hostPort: 18500
    protocol: TCP