kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # Istio Ingress Gateway: Maps port 13000 on your host to port 30000 on the Kind node.
  - containerPort: 30000
    hostPort: 13000
    protocol: TCP
  # Kafka External: Maps port 29092 on your host to port 30992 on the Kind node.
  - containerPort: 30992 # This MUST match the nodePort in the kafka-svc definition
    hostPort: 29092
    protocol: TCP
  # Elasticsearch: Maps port 9200 on your host to port 32200 on the Kind node.
  - containerPort: 32200
    hostPort: 9200
    protocol: TCP
  # Redis: Maps port 6379 on your host to port 32379 on the Kind node.
  - containerPort: 32379
    hostPort: 6379
    protocol: TCP